import Typography from '@mui/material/Typography';
import Box from '@mui/material/Box';
import Section from '../components/Section.jsx';

export default function PrivacyPage() {
    return (
        <Section sx={{ pt: 2 }}>
            <Box sx={{ maxWidth: 900 }}>
                <Typography variant="h3" component="h1" gutterBottom>
                Privacy Policy
                </Typography>

                <Typography variant="body2" color="text.secondary" paragraph>
                Last updated: October 20, 2025
                </Typography>

                <Typography variant="body2" color="text.secondary" paragraph>
                This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of
                Your information when You use the Service and tells You about Your privacy rights and how the law
                protects You.
                </Typography>

                <Typography variant="body2" color="text.secondary" paragraph>
                We use Your Personal data to provide and improve the Service. By using the Service, You agree to the
                collection and use of information in accordance with this Privacy Policy. This Privacy Policy has
                been created with the help of the Free Privacy Policy Generator (
                <a href="https://www.freeprivacypolicy.com/free-privacy-policy-generator/" target="_blank" rel="noreferrer">freeprivacypolicy.com</a>).
                </Typography>

                <Typography variant="h5" gutterBottom sx={{ mt: 2 }}>
                Interpretation and Definitions
                </Typography>

                <Typography variant="h6" gutterBottom>
                Interpretation
                </Typography>
                <Typography variant="body2" color="text.secondary" paragraph>
                The words whose initial letters are capitalized have meanings defined under the following conditions.
                The following definitions shall have the same meaning regardless of whether they appear in singular or
                in plural.
                </Typography>

                <Typography variant="h6" gutterBottom>
                Definitions
                </Typography>
                <Typography variant="body2" color="text.secondary" paragraph>
                For the purposes of this Privacy Policy:
                </Typography>

                <Box component="ul" sx={{ pl: 3, color: 'text.secondary' }}>
                <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
                <li><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
                <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Josiah Ledua | Portfolio.</li>
                <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
                <li><strong>Country</strong> refers to: Ontario, Canada</li>
                <li><strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</li>
                <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
                <li><strong>Service</strong> refers to the Website.</li>
                <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
                <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
                <li><strong>Website</strong> refers to Josiah Ledua | Portfolio, accessible from <a href="https://josiah.ledua.ca/" target="_blank" rel="noreferrer">https://josiah.ledua.ca/</a></li>
                <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
                </Box>

                <Typography variant="h5" gutterBottom sx={{ mt: 2 }}>
                Collecting and Using Your Personal Data
                </Typography>

                <Typography variant="h6" gutterBottom>
                Types of Data Collected
                </Typography>

                <Typography variant="h6">Personal Data</Typography>
                <Typography variant="body2" color="text.secondary" paragraph>
                While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
                </Typography>
                <Box component="ul" sx={{ pl: 3, color: 'text.secondary' }}>
                <li>Email address</li>
                <li>First name and last name</li>
                <li>Usage Data</li>
                </Box>

                <Typography variant="h6">Usage Data</Typography>
                <Typography variant="body2" color="text.secondary" paragraph>
                Usage Data is collected automatically when using the Service.
                </Typography>
                <Typography variant="body2" color="text.secondary" paragraph>
                Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
                </Typography>

                <Typography variant="h6">Tracking Technologies and Cookies</Typography>
                <Typography variant="body2" color="text.secondary" paragraph>
                We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies We use include beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:
                </Typography>
                <Box component="ul" sx={{ pl: 3, color: 'text.secondary' }}>
                <li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</li>
                <li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics.</li>
                </Box>

                <Typography variant="body2" color="text.secondary" paragraph>
                Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser. Learn more about cookies on the Free Privacy Policy website.
                </Typography>

                <Typography variant="h6">Use of Your Personal Data</Typography>
                <Typography variant="body2" color="text.secondary" paragraph>
                The Company may use Personal Data for the following purposes:
                </Typography>
                <Box component="ul" sx={{ pl: 3, color: 'text.secondary' }}>
                <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
                <li>To manage Your Account: to manage Your registration as a user of the Service.</li>
                <li>For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
                <li>To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.</li>
                <li>To provide You with news, special offers, and general information about other goods, services and events which We offer.</li>
                <li>To manage Your requests: To attend and manage Your requests to Us.</li>
                <li>For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets.</li>
                <li>For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</li>
                </Box>

                <Typography variant="h6">Retention of Your Personal Data</Typography>
                <Typography variant="body2" color="text.secondary" paragraph>
                The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy.
                </Typography>

                <Typography variant="h6">Transfer of Your Personal Data</Typography>
                <Typography variant="body2" color="text.secondary" paragraph>
                Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located.
                </Typography>

                <Typography variant="h6">Delete Your Personal Data</Typography>
                <Typography variant="body2" color="text.secondary" paragraph>
                You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.
                </Typography>

                <Typography variant="h6">Disclosure of Your Personal Data</Typography>
                <Typography variant="body2" color="text.secondary" paragraph>
                The Company may disclose Your Personal Data in various situations, including business transactions, law enforcement requests, and other legal requirements.
                </Typography>

                <Typography variant="h6">Security of Your Personal Data</Typography>
                <Typography variant="body2" color="text.secondary" paragraph>
                The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure.
                </Typography>

                <Typography variant="h6">Children's Privacy</Typography>
                <Typography variant="body2" color="text.secondary" paragraph>
                Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13.
                </Typography>

                <Typography variant="h6">Links to Other Websites</Typography>
                <Typography variant="body2" color="text.secondary" paragraph>
                Our Service may contain links to other websites that are not operated by Us. We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
                </Typography>

                <Typography variant="h6">Changes to this Privacy Policy</Typography>
                <Typography variant="body2" color="text.secondary" paragraph>
                We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
                </Typography>

                <Typography variant="h6">Contact Us</Typography>
                <Typography variant="body2" color="text.secondary" paragraph>
                If you have any questions about this Privacy Policy, You can contact us by visiting this page on our website: <a href="https://josiah.ledua.ca/contact">https://josiah.ledua.ca/contact</a>
                </Typography>
            </Box>
        </Section>
    );
}
